require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

AllCops:
  Exclude:
    - 'tmp/**/*'
    - 'db/**/*'
    - 'bin/**/*'

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/EndOfLine:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false      

Metrics/BlockLength:
  Max: 50

Metrics/MethodLength:
  Max: 50    